service: pyATNAP

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - client/**

functions:
  app:
    handler: wsgi.handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'